/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.prokarma.pkmst.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.simp.SimpMessageHeaderAccessor;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.prokarma.pkmst.model.Order;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
/**
 * Provides the info about api methods
 * @author pkmst
 *
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaPKMSTServerCodegen", date = "2018-02-22T21:37:34.360Z")

@Api(value = "Order", description = "the Order API")
public interface OrderApi {

    @ApiOperation(value = "Place a new order", notes = "Place a new Order. In addition to order details, it will also contain customer information and payment details", response = Void.class, tags={ "order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Order was placed") })
    @RequestMapping(value = "/order/place",
        method = RequestMethod.POST)
    ResponseEntity<Void> placeOrder(@ApiParam(value = "Object representing the order being placed"  )   @RequestBody Order body, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

    @MessageMapping("/place")
    //@SendTo("/topic/order-placed")
    public void placeOrder(SimpMessageHeaderAccessor accessor, Order order);
}
