/*
 * Foreign Exchange Lookup
 * Foreign Exchange Lookup
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import org.junit.Ignore;
import org.junit.Test;
import org.springframework.http.ResponseEntity;

import com.prokarma.pkmst.model.Forex;

/**
 * API tests for ForexApi
 */
@Ignore
public class ForexApiTest {

    private final ForexApi api = new ForexApiController();

    /**
     * Lookup a forex detail by the ticker
     *
     * Returns details of a single foreign exchange pair representer by a ticker
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getForexSummaryByTickerTest() throws Exception {
        String ticker = null;
    ResponseEntity<Forex> response = api.getForexSummaryByTicker(ticker);

        // TODO: test validations
    }
    
}
