/*
 * Car CRUD(JPA) operations
 * This is about CRUD operations of Car using JPA created by Swagger.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.Car;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for CarApi
 */
@Ignore
public class CarApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final CarApi api = new CarApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Create Car
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCarTest() throws Exception {
        Car body = null;
    ResponseEntity<Void> response = api.createCar(body , accept);

        // TODO: test validations
    }
    
    /**
     * Creates list of cars with given input array
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCarsWithArrayInputTest() throws Exception {
        List<Car> body = null;
    ResponseEntity<Void> response = api.createCarsWithArrayInput(body , accept);

        // TODO: test validations
    }
    
    /**
     * Delete car
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCarTest() throws Exception {
        String vinNumber = null;
    ResponseEntity<Void> response = api.deleteCar(vinNumber , accept);

        // TODO: test validations
    }
    
    /**
     * Get car by vin number
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByVinNumberTest() throws Exception {
        String vinNumber = null;
    ResponseEntity<Car> response = api.getCarByVinNumber(vinNumber , accept);

        // TODO: test validations
    }
    
    /**
     * Updated car
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCarTest() throws Exception {
        String vinNumber = null;
        Car body = null;
    ResponseEntity<Void> response = api.updateCar(vinNumber, body , accept);

        // TODO: test validations
    }
    
}
