/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.0-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.prokarma.pkmst.controller;

import io.swagger.annotations.Api;

import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
/**
 * Provides the info about api methods
 * @author pkmst
 *
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.PkmstServerCodegen", date = "2017-10-13T15:19:53.170Z")

@Api(value = "user", description = "the user API")
public interface HelloWorldApi {
	@RequestMapping("/hello/{name}")
	public String greetHello(@PathVariable("name") String userName);
	
	@RequestMapping("/sayHello")
	public String sayHello(@RequestParam(value="name", defaultValue="World") String userName);
}
