/*
 * Hello World App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for HelloApi
 */
@Ignore
public class HelloApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final HelloApi api = new HelloApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * 
     *
     * Returns &#39;Hello&#39; to the caller
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void helloTest() throws Exception {
        String name = null;
    ResponseEntity<InlineResponse200> response = api.hello(name , accept);

        // TODO: test validations
    }
    
}
