/*
 * Swagger Employee
 * This is a sample Hello World.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.springframework.http.ResponseEntity;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * API tests for HelloApi
 */
@Ignore
public class HelloApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @InjectMocks
    private final HelloApi api = new HelloApiController(objectMapper);

    private final String accept = "application/json";

    
    @Test
    public void createCarTest() throws Exception {
        ResponseEntity<String> response = api.greetMessage("TestUser" , accept);
        Assert.assertNotNull(response.getBody());
    }
    
}
