/*
 * Order Management
 * An API for managing Orders
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.Order;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for OrderApi
 */
@Ignore
public class OrderApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final OrderApi api = new OrderApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Place a new order
     *
     * Place a new Order. In addition to order details, it will also contain customer information and payment details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void placeOrderTest() throws Exception {
        Order body = null;
    ResponseEntity<Void> response = api.placeOrder(body , accept);

        // TODO: test validations
    }
    
}
